name: cs323-spring-2023-env

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - bokeh
  - datashader
  - gh
  - git
  - holoviews
  - hvplot
  - ipywidgets
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-nvdashboard
  - jupyterlab-lsp
  - kornia
  - matplotlib
  - nbgitpuller
  - numba
  - numpy
  - optuna
  - pandas
  - panel
  - pip
  - pip:
    - -r requirements.txt
  - pyarrow
  - python=3.10
  - python-language-server
  - pytorch=1.13
  - pytorch-cuda=11.6
  - pytorch-lightning
  - pyviz_comms
  - scikit-learn
  - scipy
  - tensorboard
  - torchaudio
  - torchmetrics
  - torchtext
  - torchvision
  - wandb
